//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiAlarmaV2.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Alarmas
    {
        public int Id { get; set; }
        public string CedulaUsuario { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> DescripcionPer { get; set; }

        [JsonIgnore]
        public virtual Descripciones Descripciones { get; set; }
        [JsonIgnore]
        public virtual Usuarios Usuarios { get; set; }
    }
}
