//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiAlarmaV2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using System.Collections.Generic;

    public partial class AlarmasComunitariasEntities3 : DbContext
    {
        public AlarmasComunitariasEntities3()
            : base("name=AlarmasComunitariasEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alarmas> Alarmas { get; set; }
        public virtual DbSet<Descripciones> Descripciones { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }


        public virtual List<VIEWADMIN_Result> VIEWADMIN()
        {
            return Database.SqlQuery<VIEWADMIN_Result>("EXECUTE dbo.VIEWADMIN").ToList();
        }

        public virtual List<ViewFechas_Result> ViewFechas()
        {
            var result = ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ViewFechas_Result>("ViewFechas");
            return result.ToList();
        }

        public virtual List<ViewFechasSector_Result> ViewFechasSector()
        {
            var result = ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ViewFechasSector_Result>("ViewFechasSector");
            return result.ToList();

        }
    }
}
