//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWebAspnet.proxyProductosWcf {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://schemas.datacontract.org/2004/07/Entidad")]
    [System.SerializableAttribute()]
    public partial class Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DiscontinuedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuantityPerUnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal UnitPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UnitsInStockField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Discontinued {
            get {
                return this.DiscontinuedField;
            }
            set {
                if ((this.DiscontinuedField.Equals(value) != true)) {
                    this.DiscontinuedField = value;
                    this.RaisePropertyChanged("Discontinued");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuantityPerUnit {
            get {
                return this.QuantityPerUnitField;
            }
            set {
                if ((object.ReferenceEquals(this.QuantityPerUnitField, value) != true)) {
                    this.QuantityPerUnitField = value;
                    this.RaisePropertyChanged("QuantityPerUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal UnitPrice {
            get {
                return this.UnitPriceField;
            }
            set {
                if ((this.UnitPriceField.Equals(value) != true)) {
                    this.UnitPriceField = value;
                    this.RaisePropertyChanged("UnitPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UnitsInStock {
            get {
                return this.UnitsInStockField;
            }
            set {
                if ((this.UnitsInStockField.Equals(value) != true)) {
                    this.UnitsInStockField = value;
                    this.RaisePropertyChanged("UnitsInStock");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="proxyProductosWcf.IwcfProductos")]
    public interface IwcfProductos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfProductos/DevolverTodosLosProductos", ReplyAction="http://tempuri.org/IwcfProductos/DevolverTodosLosProductosResponse")]
        ClienteWebAspnet.proxyProductosWcf.Producto[] DevolverTodosLosProductos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfProductos/DevolverTodosLosProductos", ReplyAction="http://tempuri.org/IwcfProductos/DevolverTodosLosProductosResponse")]
        System.Threading.Tasks.Task<ClienteWebAspnet.proxyProductosWcf.Producto[]> DevolverTodosLosProductosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfProductos/DevolverTodosLosProductosConStockCero", ReplyAction="http://tempuri.org/IwcfProductos/DevolverTodosLosProductosConStockCeroResponse")]
        ClienteWebAspnet.proxyProductosWcf.Producto[] DevolverTodosLosProductosConStockCero();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfProductos/DevolverTodosLosProductosConStockCero", ReplyAction="http://tempuri.org/IwcfProductos/DevolverTodosLosProductosConStockCeroResponse")]
        System.Threading.Tasks.Task<ClienteWebAspnet.proxyProductosWcf.Producto[]> DevolverTodosLosProductosConStockCeroAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfProductos/DevolverTodosLosProductosDescontinuados", ReplyAction="http://tempuri.org/IwcfProductos/DevolverTodosLosProductosDescontinuadosResponse")]
        ClienteWebAspnet.proxyProductosWcf.Producto[] DevolverTodosLosProductosDescontinuados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfProductos/DevolverTodosLosProductosDescontinuados", ReplyAction="http://tempuri.org/IwcfProductos/DevolverTodosLosProductosDescontinuadosResponse")]
        System.Threading.Tasks.Task<ClienteWebAspnet.proxyProductosWcf.Producto[]> DevolverTodosLosProductosDescontinuadosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfProductos/DevolverTodosLosProductosConRiesgoCaducarse", ReplyAction="http://tempuri.org/IwcfProductos/DevolverTodosLosProductosConRiesgoCaducarseRespo" +
            "nse")]
        ClienteWebAspnet.proxyProductosWcf.Producto[] DevolverTodosLosProductosConRiesgoCaducarse();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfProductos/DevolverTodosLosProductosConRiesgoCaducarse", ReplyAction="http://tempuri.org/IwcfProductos/DevolverTodosLosProductosConRiesgoCaducarseRespo" +
            "nse")]
        System.Threading.Tasks.Task<ClienteWebAspnet.proxyProductosWcf.Producto[]> DevolverTodosLosProductosConRiesgoCaducarseAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IwcfProductosChannel : ClienteWebAspnet.proxyProductosWcf.IwcfProductos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IwcfProductosClient : System.ServiceModel.ClientBase<ClienteWebAspnet.proxyProductosWcf.IwcfProductos>, ClienteWebAspnet.proxyProductosWcf.IwcfProductos {
        
        public IwcfProductosClient() {
        }
        
        public IwcfProductosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IwcfProductosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwcfProductosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwcfProductosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClienteWebAspnet.proxyProductosWcf.Producto[] DevolverTodosLosProductos() {
            return base.Channel.DevolverTodosLosProductos();
        }
        
        public System.Threading.Tasks.Task<ClienteWebAspnet.proxyProductosWcf.Producto[]> DevolverTodosLosProductosAsync() {
            return base.Channel.DevolverTodosLosProductosAsync();
        }
        
        public ClienteWebAspnet.proxyProductosWcf.Producto[] DevolverTodosLosProductosConStockCero() {
            return base.Channel.DevolverTodosLosProductosConStockCero();
        }
        
        public System.Threading.Tasks.Task<ClienteWebAspnet.proxyProductosWcf.Producto[]> DevolverTodosLosProductosConStockCeroAsync() {
            return base.Channel.DevolverTodosLosProductosConStockCeroAsync();
        }
        
        public ClienteWebAspnet.proxyProductosWcf.Producto[] DevolverTodosLosProductosDescontinuados() {
            return base.Channel.DevolverTodosLosProductosDescontinuados();
        }
        
        public System.Threading.Tasks.Task<ClienteWebAspnet.proxyProductosWcf.Producto[]> DevolverTodosLosProductosDescontinuadosAsync() {
            return base.Channel.DevolverTodosLosProductosDescontinuadosAsync();
        }
        
        public ClienteWebAspnet.proxyProductosWcf.Producto[] DevolverTodosLosProductosConRiesgoCaducarse() {
            return base.Channel.DevolverTodosLosProductosConRiesgoCaducarse();
        }
        
        public System.Threading.Tasks.Task<ClienteWebAspnet.proxyProductosWcf.Producto[]> DevolverTodosLosProductosConRiesgoCaducarseAsync() {
            return base.Channel.DevolverTodosLosProductosConRiesgoCaducarseAsync();
        }
    }
}
