#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BaseMaps")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertUBICACION(UBICACION instance);
    partial void UpdateUBICACION(UBICACION instance);
    partial void DeleteUBICACION(UBICACION instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Datos.Properties.Settings.Default.BaseMapsConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<UBICACION> UBICACION
		{
			get
			{
				return this.GetTable<UBICACION>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UBICACION")]
	public partial class UBICACION : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdNegocioCliente;
		
		private string _NombreCliente;
		
		private string _ApellidoCliente;
		
		private string _NombreNegocio;
		
		private string _TipoNegocio;
		
		private string _Direccion;
		
		private System.Nullable<decimal> _Latitud;
		
		private System.Nullable<decimal> _Longitud;
		
		private string _HorarioAtencion;
		
		private string _Telefono;
		
		private string _Descripcion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdNegocioClienteChanging(int value);
    partial void OnIdNegocioClienteChanged();
    partial void OnNombreClienteChanging(string value);
    partial void OnNombreClienteChanged();
    partial void OnApellidoClienteChanging(string value);
    partial void OnApellidoClienteChanged();
    partial void OnNombreNegocioChanging(string value);
    partial void OnNombreNegocioChanged();
    partial void OnTipoNegocioChanging(string value);
    partial void OnTipoNegocioChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnLatitudChanging(System.Nullable<decimal> value);
    partial void OnLatitudChanged();
    partial void OnLongitudChanging(System.Nullable<decimal> value);
    partial void OnLongitudChanged();
    partial void OnHorarioAtencionChanging(string value);
    partial void OnHorarioAtencionChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    #endregion
		
		public UBICACION()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdNegocioCliente", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdNegocioCliente
		{
			get
			{
				return this._IdNegocioCliente;
			}
			set
			{
				if ((this._IdNegocioCliente != value))
				{
					this.OnIdNegocioClienteChanging(value);
					this.SendPropertyChanging();
					this._IdNegocioCliente = value;
					this.SendPropertyChanged("IdNegocioCliente");
					this.OnIdNegocioClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreCliente", DbType="NVarChar(50)")]
		public string NombreCliente
		{
			get
			{
				return this._NombreCliente;
			}
			set
			{
				if ((this._NombreCliente != value))
				{
					this.OnNombreClienteChanging(value);
					this.SendPropertyChanging();
					this._NombreCliente = value;
					this.SendPropertyChanged("NombreCliente");
					this.OnNombreClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApellidoCliente", DbType="NVarChar(50)")]
		public string ApellidoCliente
		{
			get
			{
				return this._ApellidoCliente;
			}
			set
			{
				if ((this._ApellidoCliente != value))
				{
					this.OnApellidoClienteChanging(value);
					this.SendPropertyChanging();
					this._ApellidoCliente = value;
					this.SendPropertyChanged("ApellidoCliente");
					this.OnApellidoClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreNegocio", DbType="NVarChar(50)")]
		public string NombreNegocio
		{
			get
			{
				return this._NombreNegocio;
			}
			set
			{
				if ((this._NombreNegocio != value))
				{
					this.OnNombreNegocioChanging(value);
					this.SendPropertyChanging();
					this._NombreNegocio = value;
					this.SendPropertyChanged("NombreNegocio");
					this.OnNombreNegocioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoNegocio", DbType="NVarChar(50)")]
		public string TipoNegocio
		{
			get
			{
				return this._TipoNegocio;
			}
			set
			{
				if ((this._TipoNegocio != value))
				{
					this.OnTipoNegocioChanging(value);
					this.SendPropertyChanging();
					this._TipoNegocio = value;
					this.SendPropertyChanged("TipoNegocio");
					this.OnTipoNegocioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="NVarChar(50)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Latitud", DbType="Decimal(9,6)")]
		public System.Nullable<decimal> Latitud
		{
			get
			{
				return this._Latitud;
			}
			set
			{
				if ((this._Latitud != value))
				{
					this.OnLatitudChanging(value);
					this.SendPropertyChanging();
					this._Latitud = value;
					this.SendPropertyChanged("Latitud");
					this.OnLatitudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Longitud", DbType="Decimal(9,6)")]
		public System.Nullable<decimal> Longitud
		{
			get
			{
				return this._Longitud;
			}
			set
			{
				if ((this._Longitud != value))
				{
					this.OnLongitudChanging(value);
					this.SendPropertyChanging();
					this._Longitud = value;
					this.SendPropertyChanged("Longitud");
					this.OnLongitudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HorarioAtencion", DbType="NVarChar(100)")]
		public string HorarioAtencion
		{
			get
			{
				return this._HorarioAtencion;
			}
			set
			{
				if ((this._HorarioAtencion != value))
				{
					this.OnHorarioAtencionChanging(value);
					this.SendPropertyChanging();
					this._HorarioAtencion = value;
					this.SendPropertyChanged("HorarioAtencion");
					this.OnHorarioAtencionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="NVarChar(20)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="NVarChar(500)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
