//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWebServicios.ProxyListaUsuario {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NacionalidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Cedula {
            get {
                return this.CedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.CedulaField, value) != true)) {
                    this.CedulaField = value;
                    this.RaisePropertyChanged("Cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Nacionalidad {
            get {
                return this.NacionalidadField;
            }
            set {
                if ((object.ReferenceEquals(this.NacionalidadField, value) != true)) {
                    this.NacionalidadField = value;
                    this.RaisePropertyChanged("Nacionalidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyListaUsuario.WebServiceUsuariosSoap")]
    public interface WebServiceUsuariosSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListadoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listado", ReplyAction="*")]
        ClienteWebServicios.ProxyListaUsuario.ListadoResponse Listado(ClienteWebServicios.ProxyListaUsuario.ListadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listado", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteWebServicios.ProxyListaUsuario.ListadoResponse> ListadoAsync(ClienteWebServicios.ProxyListaUsuario.ListadoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Listado", Namespace="http://tempuri.org/", Order=0)]
        public ClienteWebServicios.ProxyListaUsuario.ListadoRequestBody Body;
        
        public ListadoRequest() {
        }
        
        public ListadoRequest(ClienteWebServicios.ProxyListaUsuario.ListadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListadoRequestBody {
        
        public ListadoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListadoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteWebServicios.ProxyListaUsuario.ListadoResponseBody Body;
        
        public ListadoResponse() {
        }
        
        public ListadoResponse(ClienteWebServicios.ProxyListaUsuario.ListadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListadoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClienteWebServicios.ProxyListaUsuario.Usuario[] ListadoResult;
        
        public ListadoResponseBody() {
        }
        
        public ListadoResponseBody(ClienteWebServicios.ProxyListaUsuario.Usuario[] ListadoResult) {
            this.ListadoResult = ListadoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceUsuariosSoapChannel : ClienteWebServicios.ProxyListaUsuario.WebServiceUsuariosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceUsuariosSoapClient : System.ServiceModel.ClientBase<ClienteWebServicios.ProxyListaUsuario.WebServiceUsuariosSoap>, ClienteWebServicios.ProxyListaUsuario.WebServiceUsuariosSoap {
        
        public WebServiceUsuariosSoapClient() {
        }
        
        public WebServiceUsuariosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceUsuariosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceUsuariosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceUsuariosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteWebServicios.ProxyListaUsuario.ListadoResponse ClienteWebServicios.ProxyListaUsuario.WebServiceUsuariosSoap.Listado(ClienteWebServicios.ProxyListaUsuario.ListadoRequest request) {
            return base.Channel.Listado(request);
        }
        
        public ClienteWebServicios.ProxyListaUsuario.Usuario[] Listado() {
            ClienteWebServicios.ProxyListaUsuario.ListadoRequest inValue = new ClienteWebServicios.ProxyListaUsuario.ListadoRequest();
            inValue.Body = new ClienteWebServicios.ProxyListaUsuario.ListadoRequestBody();
            ClienteWebServicios.ProxyListaUsuario.ListadoResponse retVal = ((ClienteWebServicios.ProxyListaUsuario.WebServiceUsuariosSoap)(this)).Listado(inValue);
            return retVal.Body.ListadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteWebServicios.ProxyListaUsuario.ListadoResponse> ClienteWebServicios.ProxyListaUsuario.WebServiceUsuariosSoap.ListadoAsync(ClienteWebServicios.ProxyListaUsuario.ListadoRequest request) {
            return base.Channel.ListadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteWebServicios.ProxyListaUsuario.ListadoResponse> ListadoAsync() {
            ClienteWebServicios.ProxyListaUsuario.ListadoRequest inValue = new ClienteWebServicios.ProxyListaUsuario.ListadoRequest();
            inValue.Body = new ClienteWebServicios.ProxyListaUsuario.ListadoRequestBody();
            return ((ClienteWebServicios.ProxyListaUsuario.WebServiceUsuariosSoap)(this)).ListadoAsync(inValue);
        }
    }
}
