//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWebAspnet.ProxyProductos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuantityPerUnitField;
        
        private decimal UnitPriceField;
        
        private int UnitsInStockField;
        
        private bool DiscontinuedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string QuantityPerUnit {
            get {
                return this.QuantityPerUnitField;
            }
            set {
                if ((object.ReferenceEquals(this.QuantityPerUnitField, value) != true)) {
                    this.QuantityPerUnitField = value;
                    this.RaisePropertyChanged("QuantityPerUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal UnitPrice {
            get {
                return this.UnitPriceField;
            }
            set {
                if ((this.UnitPriceField.Equals(value) != true)) {
                    this.UnitPriceField = value;
                    this.RaisePropertyChanged("UnitPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UnitsInStock {
            get {
                return this.UnitsInStockField;
            }
            set {
                if ((this.UnitsInStockField.Equals(value) != true)) {
                    this.UnitsInStockField = value;
                    this.RaisePropertyChanged("UnitsInStock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool Discontinued {
            get {
                return this.DiscontinuedField;
            }
            set {
                if ((this.DiscontinuedField.Equals(value) != true)) {
                    this.DiscontinuedField = value;
                    this.RaisePropertyChanged("Discontinued");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyProductos.wsProductosSoap")]
    public interface wsProductosSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento DevolverTodosLosProductosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DevolverTodosLosProductos", ReplyAction="*")]
        ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosResponse DevolverTodosLosProductos(ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DevolverTodosLosProductos", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosResponse> DevolverTodosLosProductosAsync(ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento DevolverTodosLosProductosConStockCeroResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DevolverTodosLosProductosConStockCero", ReplyAction="*")]
        ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosConStockCeroResponse DevolverTodosLosProductosConStockCero(ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosConStockCeroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DevolverTodosLosProductosConStockCero", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosConStockCeroResponse> DevolverTodosLosProductosConStockCeroAsync(ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosConStockCeroRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento DevolverTodosLosProductosDescontinuadosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DevolverTodosLosProductosDescontinuados", ReplyAction="*")]
        ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosDescontinuadosResponse DevolverTodosLosProductosDescontinuados(ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosDescontinuadosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DevolverTodosLosProductosDescontinuados", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosDescontinuadosResponse> DevolverTodosLosProductosDescontinuadosAsync(ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosDescontinuadosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento DevolverTodosLosProductosConRiesgoCaducarseResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DevolverTodosLosProductosConRiesgoCaducarse", ReplyAction="*")]
        ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosConRiesgoCaducarseResponse DevolverTodosLosProductosConRiesgoCaducarse(ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosConRiesgoCaducarseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DevolverTodosLosProductosConRiesgoCaducarse", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosConRiesgoCaducarseResponse> DevolverTodosLosProductosConRiesgoCaducarseAsync(ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosConRiesgoCaducarseRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DevolverTodosLosProductosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DevolverTodosLosProductos", Namespace="http://tempuri.org/", Order=0)]
        public ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosRequestBody Body;
        
        public DevolverTodosLosProductosRequest() {
        }
        
        public DevolverTodosLosProductosRequest(ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DevolverTodosLosProductosRequestBody {
        
        public DevolverTodosLosProductosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DevolverTodosLosProductosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DevolverTodosLosProductosResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosResponseBody Body;
        
        public DevolverTodosLosProductosResponse() {
        }
        
        public DevolverTodosLosProductosResponse(ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DevolverTodosLosProductosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClienteWebAspnet.ProxyProductos.Producto[] DevolverTodosLosProductosResult;
        
        public DevolverTodosLosProductosResponseBody() {
        }
        
        public DevolverTodosLosProductosResponseBody(ClienteWebAspnet.ProxyProductos.Producto[] DevolverTodosLosProductosResult) {
            this.DevolverTodosLosProductosResult = DevolverTodosLosProductosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DevolverTodosLosProductosConStockCeroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DevolverTodosLosProductosConStockCero", Namespace="http://tempuri.org/", Order=0)]
        public ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosConStockCeroRequestBody Body;
        
        public DevolverTodosLosProductosConStockCeroRequest() {
        }
        
        public DevolverTodosLosProductosConStockCeroRequest(ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosConStockCeroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DevolverTodosLosProductosConStockCeroRequestBody {
        
        public DevolverTodosLosProductosConStockCeroRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DevolverTodosLosProductosConStockCeroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DevolverTodosLosProductosConStockCeroResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosConStockCeroResponseBody Body;
        
        public DevolverTodosLosProductosConStockCeroResponse() {
        }
        
        public DevolverTodosLosProductosConStockCeroResponse(ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosConStockCeroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DevolverTodosLosProductosConStockCeroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClienteWebAspnet.ProxyProductos.Producto[] DevolverTodosLosProductosConStockCeroResult;
        
        public DevolverTodosLosProductosConStockCeroResponseBody() {
        }
        
        public DevolverTodosLosProductosConStockCeroResponseBody(ClienteWebAspnet.ProxyProductos.Producto[] DevolverTodosLosProductosConStockCeroResult) {
            this.DevolverTodosLosProductosConStockCeroResult = DevolverTodosLosProductosConStockCeroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DevolverTodosLosProductosDescontinuadosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DevolverTodosLosProductosDescontinuados", Namespace="http://tempuri.org/", Order=0)]
        public ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosDescontinuadosRequestBody Body;
        
        public DevolverTodosLosProductosDescontinuadosRequest() {
        }
        
        public DevolverTodosLosProductosDescontinuadosRequest(ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosDescontinuadosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DevolverTodosLosProductosDescontinuadosRequestBody {
        
        public DevolverTodosLosProductosDescontinuadosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DevolverTodosLosProductosDescontinuadosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DevolverTodosLosProductosDescontinuadosResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosDescontinuadosResponseBody Body;
        
        public DevolverTodosLosProductosDescontinuadosResponse() {
        }
        
        public DevolverTodosLosProductosDescontinuadosResponse(ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosDescontinuadosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DevolverTodosLosProductosDescontinuadosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClienteWebAspnet.ProxyProductos.Producto[] DevolverTodosLosProductosDescontinuadosResult;
        
        public DevolverTodosLosProductosDescontinuadosResponseBody() {
        }
        
        public DevolverTodosLosProductosDescontinuadosResponseBody(ClienteWebAspnet.ProxyProductos.Producto[] DevolverTodosLosProductosDescontinuadosResult) {
            this.DevolverTodosLosProductosDescontinuadosResult = DevolverTodosLosProductosDescontinuadosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DevolverTodosLosProductosConRiesgoCaducarseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DevolverTodosLosProductosConRiesgoCaducarse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosConRiesgoCaducarseRequestBody Body;
        
        public DevolverTodosLosProductosConRiesgoCaducarseRequest() {
        }
        
        public DevolverTodosLosProductosConRiesgoCaducarseRequest(ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosConRiesgoCaducarseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DevolverTodosLosProductosConRiesgoCaducarseRequestBody {
        
        public DevolverTodosLosProductosConRiesgoCaducarseRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DevolverTodosLosProductosConRiesgoCaducarseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DevolverTodosLosProductosConRiesgoCaducarseResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosConRiesgoCaducarseResponseBody Body;
        
        public DevolverTodosLosProductosConRiesgoCaducarseResponse() {
        }
        
        public DevolverTodosLosProductosConRiesgoCaducarseResponse(ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosConRiesgoCaducarseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DevolverTodosLosProductosConRiesgoCaducarseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClienteWebAspnet.ProxyProductos.Producto[] DevolverTodosLosProductosConRiesgoCaducarseResult;
        
        public DevolverTodosLosProductosConRiesgoCaducarseResponseBody() {
        }
        
        public DevolverTodosLosProductosConRiesgoCaducarseResponseBody(ClienteWebAspnet.ProxyProductos.Producto[] DevolverTodosLosProductosConRiesgoCaducarseResult) {
            this.DevolverTodosLosProductosConRiesgoCaducarseResult = DevolverTodosLosProductosConRiesgoCaducarseResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsProductosSoapChannel : ClienteWebAspnet.ProxyProductos.wsProductosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsProductosSoapClient : System.ServiceModel.ClientBase<ClienteWebAspnet.ProxyProductos.wsProductosSoap>, ClienteWebAspnet.ProxyProductos.wsProductosSoap {
        
        public wsProductosSoapClient() {
        }
        
        public wsProductosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsProductosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsProductosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsProductosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosResponse ClienteWebAspnet.ProxyProductos.wsProductosSoap.DevolverTodosLosProductos(ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosRequest request) {
            return base.Channel.DevolverTodosLosProductos(request);
        }
        
        public ClienteWebAspnet.ProxyProductos.Producto[] DevolverTodosLosProductos() {
            ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosRequest inValue = new ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosRequest();
            inValue.Body = new ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosRequestBody();
            ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosResponse retVal = ((ClienteWebAspnet.ProxyProductos.wsProductosSoap)(this)).DevolverTodosLosProductos(inValue);
            return retVal.Body.DevolverTodosLosProductosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosResponse> ClienteWebAspnet.ProxyProductos.wsProductosSoap.DevolverTodosLosProductosAsync(ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosRequest request) {
            return base.Channel.DevolverTodosLosProductosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosResponse> DevolverTodosLosProductosAsync() {
            ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosRequest inValue = new ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosRequest();
            inValue.Body = new ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosRequestBody();
            return ((ClienteWebAspnet.ProxyProductos.wsProductosSoap)(this)).DevolverTodosLosProductosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosConStockCeroResponse ClienteWebAspnet.ProxyProductos.wsProductosSoap.DevolverTodosLosProductosConStockCero(ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosConStockCeroRequest request) {
            return base.Channel.DevolverTodosLosProductosConStockCero(request);
        }
        
        public ClienteWebAspnet.ProxyProductos.Producto[] DevolverTodosLosProductosConStockCero() {
            ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosConStockCeroRequest inValue = new ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosConStockCeroRequest();
            inValue.Body = new ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosConStockCeroRequestBody();
            ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosConStockCeroResponse retVal = ((ClienteWebAspnet.ProxyProductos.wsProductosSoap)(this)).DevolverTodosLosProductosConStockCero(inValue);
            return retVal.Body.DevolverTodosLosProductosConStockCeroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosConStockCeroResponse> ClienteWebAspnet.ProxyProductos.wsProductosSoap.DevolverTodosLosProductosConStockCeroAsync(ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosConStockCeroRequest request) {
            return base.Channel.DevolverTodosLosProductosConStockCeroAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosConStockCeroResponse> DevolverTodosLosProductosConStockCeroAsync() {
            ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosConStockCeroRequest inValue = new ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosConStockCeroRequest();
            inValue.Body = new ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosConStockCeroRequestBody();
            return ((ClienteWebAspnet.ProxyProductos.wsProductosSoap)(this)).DevolverTodosLosProductosConStockCeroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosDescontinuadosResponse ClienteWebAspnet.ProxyProductos.wsProductosSoap.DevolverTodosLosProductosDescontinuados(ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosDescontinuadosRequest request) {
            return base.Channel.DevolverTodosLosProductosDescontinuados(request);
        }
        
        public ClienteWebAspnet.ProxyProductos.Producto[] DevolverTodosLosProductosDescontinuados() {
            ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosDescontinuadosRequest inValue = new ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosDescontinuadosRequest();
            inValue.Body = new ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosDescontinuadosRequestBody();
            ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosDescontinuadosResponse retVal = ((ClienteWebAspnet.ProxyProductos.wsProductosSoap)(this)).DevolverTodosLosProductosDescontinuados(inValue);
            return retVal.Body.DevolverTodosLosProductosDescontinuadosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosDescontinuadosResponse> ClienteWebAspnet.ProxyProductos.wsProductosSoap.DevolverTodosLosProductosDescontinuadosAsync(ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosDescontinuadosRequest request) {
            return base.Channel.DevolverTodosLosProductosDescontinuadosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosDescontinuadosResponse> DevolverTodosLosProductosDescontinuadosAsync() {
            ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosDescontinuadosRequest inValue = new ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosDescontinuadosRequest();
            inValue.Body = new ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosDescontinuadosRequestBody();
            return ((ClienteWebAspnet.ProxyProductos.wsProductosSoap)(this)).DevolverTodosLosProductosDescontinuadosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosConRiesgoCaducarseResponse ClienteWebAspnet.ProxyProductos.wsProductosSoap.DevolverTodosLosProductosConRiesgoCaducarse(ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosConRiesgoCaducarseRequest request) {
            return base.Channel.DevolverTodosLosProductosConRiesgoCaducarse(request);
        }
        
        public ClienteWebAspnet.ProxyProductos.Producto[] DevolverTodosLosProductosConRiesgoCaducarse() {
            ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosConRiesgoCaducarseRequest inValue = new ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosConRiesgoCaducarseRequest();
            inValue.Body = new ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosConRiesgoCaducarseRequestBody();
            ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosConRiesgoCaducarseResponse retVal = ((ClienteWebAspnet.ProxyProductos.wsProductosSoap)(this)).DevolverTodosLosProductosConRiesgoCaducarse(inValue);
            return retVal.Body.DevolverTodosLosProductosConRiesgoCaducarseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosConRiesgoCaducarseResponse> ClienteWebAspnet.ProxyProductos.wsProductosSoap.DevolverTodosLosProductosConRiesgoCaducarseAsync(ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosConRiesgoCaducarseRequest request) {
            return base.Channel.DevolverTodosLosProductosConRiesgoCaducarseAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosConRiesgoCaducarseResponse> DevolverTodosLosProductosConRiesgoCaducarseAsync() {
            ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosConRiesgoCaducarseRequest inValue = new ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosConRiesgoCaducarseRequest();
            inValue.Body = new ClienteWebAspnet.ProxyProductos.DevolverTodosLosProductosConRiesgoCaducarseRequestBody();
            return ((ClienteWebAspnet.ProxyProductos.wsProductosSoap)(this)).DevolverTodosLosProductosConRiesgoCaducarseAsync(inValue);
        }
    }
}
