//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWCF.proxyServiciosEjemplos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="proxyServiciosEjemplos.IIServicioEjemplosWfc")]
    public interface IIServicioEjemplosWfc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIServicioEjemplosWfc/Saludo", ReplyAction="http://tempuri.org/IIServicioEjemplosWfc/SaludoResponse")]
        string Saludo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIServicioEjemplosWfc/Saludo", ReplyAction="http://tempuri.org/IIServicioEjemplosWfc/SaludoResponse")]
        System.Threading.Tasks.Task<string> SaludoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIServicioEjemplosWfc/Potencia", ReplyAction="http://tempuri.org/IIServicioEjemplosWfc/PotenciaResponse")]
        double Potencia(double _base, double _exponente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIServicioEjemplosWfc/Potencia", ReplyAction="http://tempuri.org/IIServicioEjemplosWfc/PotenciaResponse")]
        System.Threading.Tasks.Task<double> PotenciaAsync(double _base, double _exponente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIServicioEjemplosWfc/RaizCuadrada", ReplyAction="http://tempuri.org/IIServicioEjemplosWfc/RaizCuadradaResponse")]
        double RaizCuadrada(double numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIServicioEjemplosWfc/RaizCuadrada", ReplyAction="http://tempuri.org/IIServicioEjemplosWfc/RaizCuadradaResponse")]
        System.Threading.Tasks.Task<double> RaizCuadradaAsync(double numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIServicioEjemplosWfc/GenerarNumerosPares", ReplyAction="http://tempuri.org/IIServicioEjemplosWfc/GenerarNumerosParesResponse")]
        int[] GenerarNumerosPares(int limite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIServicioEjemplosWfc/GenerarNumerosPares", ReplyAction="http://tempuri.org/IIServicioEjemplosWfc/GenerarNumerosParesResponse")]
        System.Threading.Tasks.Task<int[]> GenerarNumerosParesAsync(int limite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIServicioEjemplosWfcChannel : ClienteWCF.proxyServiciosEjemplos.IIServicioEjemplosWfc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IServicioEjemplosWfcClient : System.ServiceModel.ClientBase<ClienteWCF.proxyServiciosEjemplos.IIServicioEjemplosWfc>, ClienteWCF.proxyServiciosEjemplos.IIServicioEjemplosWfc {
        
        public IServicioEjemplosWfcClient() {
        }
        
        public IServicioEjemplosWfcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IServicioEjemplosWfcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IServicioEjemplosWfcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IServicioEjemplosWfcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Saludo() {
            return base.Channel.Saludo();
        }
        
        public System.Threading.Tasks.Task<string> SaludoAsync() {
            return base.Channel.SaludoAsync();
        }
        
        public double Potencia(double _base, double _exponente) {
            return base.Channel.Potencia(_base, _exponente);
        }
        
        public System.Threading.Tasks.Task<double> PotenciaAsync(double _base, double _exponente) {
            return base.Channel.PotenciaAsync(_base, _exponente);
        }
        
        public double RaizCuadrada(double numero) {
            return base.Channel.RaizCuadrada(numero);
        }
        
        public System.Threading.Tasks.Task<double> RaizCuadradaAsync(double numero) {
            return base.Channel.RaizCuadradaAsync(numero);
        }
        
        public int[] GenerarNumerosPares(int limite) {
            return base.Channel.GenerarNumerosPares(limite);
        }
        
        public System.Threading.Tasks.Task<int[]> GenerarNumerosParesAsync(int limite) {
            return base.Channel.GenerarNumerosParesAsync(limite);
        }
    }
}
