//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UbicacionEntidad", Namespace="http://schemas.datacontract.org/2004/07/Entidad")]
    [System.SerializableAttribute()]
    public partial class UbicacionEntidad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HorarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdNegocioClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LatitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LongitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreNegocioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoNegocioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Horario {
            get {
                return this.HorarioField;
            }
            set {
                if ((object.ReferenceEquals(this.HorarioField, value) != true)) {
                    this.HorarioField = value;
                    this.RaisePropertyChanged("Horario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdNegocioCliente {
            get {
                return this.IdNegocioClienteField;
            }
            set {
                if ((this.IdNegocioClienteField.Equals(value) != true)) {
                    this.IdNegocioClienteField = value;
                    this.RaisePropertyChanged("IdNegocioCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Latitud {
            get {
                return this.LatitudField;
            }
            set {
                if ((this.LatitudField.Equals(value) != true)) {
                    this.LatitudField = value;
                    this.RaisePropertyChanged("Latitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Longitud {
            get {
                return this.LongitudField;
            }
            set {
                if ((this.LongitudField.Equals(value) != true)) {
                    this.LongitudField = value;
                    this.RaisePropertyChanged("Longitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreNegocio {
            get {
                return this.NombreNegocioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreNegocioField, value) != true)) {
                    this.NombreNegocioField = value;
                    this.RaisePropertyChanged("NombreNegocio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoNegocio {
            get {
                return this.TipoNegocioField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoNegocioField, value) != true)) {
                    this.TipoNegocioField = value;
                    this.RaisePropertyChanged("TipoNegocio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ubicacion", Namespace="http://schemas.datacontract.org/2004/07/ServicioWCF")]
    [System.SerializableAttribute()]
    public partial class Ubicacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HorarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdNegocioClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LatitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LongitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreNegocioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoNegocioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Horario {
            get {
                return this.HorarioField;
            }
            set {
                if ((object.ReferenceEquals(this.HorarioField, value) != true)) {
                    this.HorarioField = value;
                    this.RaisePropertyChanged("Horario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdNegocioCliente {
            get {
                return this.IdNegocioClienteField;
            }
            set {
                if ((this.IdNegocioClienteField.Equals(value) != true)) {
                    this.IdNegocioClienteField = value;
                    this.RaisePropertyChanged("IdNegocioCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Latitud {
            get {
                return this.LatitudField;
            }
            set {
                if ((this.LatitudField.Equals(value) != true)) {
                    this.LatitudField = value;
                    this.RaisePropertyChanged("Latitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Longitud {
            get {
                return this.LongitudField;
            }
            set {
                if ((this.LongitudField.Equals(value) != true)) {
                    this.LongitudField = value;
                    this.RaisePropertyChanged("Longitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreNegocio {
            get {
                return this.NombreNegocioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreNegocioField, value) != true)) {
                    this.NombreNegocioField = value;
                    this.RaisePropertyChanged("NombreNegocio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoNegocio {
            get {
                return this.TipoNegocioField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoNegocioField, value) != true)) {
                    this.TipoNegocioField = value;
                    this.RaisePropertyChanged("TipoNegocio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IwcfUbicaciones")]
    public interface IwcfUbicaciones {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfUbicaciones/DevolverUbicaciones", ReplyAction="http://tempuri.org/IwcfUbicaciones/DevolverUbicacionesResponse")]
        Cliente.ServiceReference1.UbicacionEntidad[] DevolverUbicaciones();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfUbicaciones/DevolverUbicaciones", ReplyAction="http://tempuri.org/IwcfUbicaciones/DevolverUbicacionesResponse")]
        System.Threading.Tasks.Task<Cliente.ServiceReference1.UbicacionEntidad[]> DevolverUbicacionesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfUbicaciones/CrearUbicacion", ReplyAction="http://tempuri.org/IwcfUbicaciones/CrearUbicacionResponse")]
        Cliente.ServiceReference1.Ubicacion CrearUbicacion(int idNegocioCliente, string nombre, string apellido, string nombreNegocio, string tipoNegocio, string direccion, decimal latitud, decimal longitud, string horario, string telefono, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfUbicaciones/CrearUbicacion", ReplyAction="http://tempuri.org/IwcfUbicaciones/CrearUbicacionResponse")]
        System.Threading.Tasks.Task<Cliente.ServiceReference1.Ubicacion> CrearUbicacionAsync(int idNegocioCliente, string nombre, string apellido, string nombreNegocio, string tipoNegocio, string direccion, decimal latitud, decimal longitud, string horario, string telefono, string descripcion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IwcfUbicacionesChannel : Cliente.ServiceReference1.IwcfUbicaciones, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IwcfUbicacionesClient : System.ServiceModel.ClientBase<Cliente.ServiceReference1.IwcfUbicaciones>, Cliente.ServiceReference1.IwcfUbicaciones {
        
        public IwcfUbicacionesClient() {
        }
        
        public IwcfUbicacionesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IwcfUbicacionesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwcfUbicacionesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwcfUbicacionesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Cliente.ServiceReference1.UbicacionEntidad[] DevolverUbicaciones() {
            return base.Channel.DevolverUbicaciones();
        }
        
        public System.Threading.Tasks.Task<Cliente.ServiceReference1.UbicacionEntidad[]> DevolverUbicacionesAsync() {
            return base.Channel.DevolverUbicacionesAsync();
        }
        
        public Cliente.ServiceReference1.Ubicacion CrearUbicacion(int idNegocioCliente, string nombre, string apellido, string nombreNegocio, string tipoNegocio, string direccion, decimal latitud, decimal longitud, string horario, string telefono, string descripcion) {
            return base.Channel.CrearUbicacion(idNegocioCliente, nombre, apellido, nombreNegocio, tipoNegocio, direccion, latitud, longitud, horario, telefono, descripcion);
        }
        
        public System.Threading.Tasks.Task<Cliente.ServiceReference1.Ubicacion> CrearUbicacionAsync(int idNegocioCliente, string nombre, string apellido, string nombreNegocio, string tipoNegocio, string direccion, decimal latitud, decimal longitud, string horario, string telefono, string descripcion) {
            return base.Channel.CrearUbicacionAsync(idNegocioCliente, nombre, apellido, nombreNegocio, tipoNegocio, direccion, latitud, longitud, horario, telefono, descripcion);
        }
    }
}
