//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteServicio.ProxyServicioTest1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyServicioTest1.WebServiceTest1Soap")]
    public interface WebServiceTest1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento SaludosMatutinosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaludosMatutinos", ReplyAction="*")]
        ClienteServicio.ProxyServicioTest1.SaludosMatutinosResponse SaludosMatutinos(ClienteServicio.ProxyServicioTest1.SaludosMatutinosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaludosMatutinos", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteServicio.ProxyServicioTest1.SaludosMatutinosResponse> SaludosMatutinosAsync(ClienteServicio.ProxyServicioTest1.SaludosMatutinosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SumarDosNumeros", ReplyAction="*")]
        double SumarDosNumeros(double numero1, double numero2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SumarDosNumeros", ReplyAction="*")]
        System.Threading.Tasks.Task<double> SumarDosNumerosAsync(double numero1, double numero2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Potencia", ReplyAction="*")]
        double Potencia(double _base, double _exponente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Potencia", ReplyAction="*")]
        System.Threading.Tasks.Task<double> PotenciaAsync(double _base, double _exponente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LanzamientoDado", ReplyAction="*")]
        int LanzamientoDado();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LanzamientoDado", ReplyAction="*")]
        System.Threading.Tasks.Task<int> LanzamientoDadoAsync();
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento JuegoDadoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JuegoDado", ReplyAction="*")]
        ClienteServicio.ProxyServicioTest1.JuegoDadoResponse JuegoDado(ClienteServicio.ProxyServicioTest1.JuegoDadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JuegoDado", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteServicio.ProxyServicioTest1.JuegoDadoResponse> JuegoDadoAsync(ClienteServicio.ProxyServicioTest1.JuegoDadoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaludosMatutinosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaludosMatutinos", Namespace="http://tempuri.org/", Order=0)]
        public ClienteServicio.ProxyServicioTest1.SaludosMatutinosRequestBody Body;
        
        public SaludosMatutinosRequest() {
        }
        
        public SaludosMatutinosRequest(ClienteServicio.ProxyServicioTest1.SaludosMatutinosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SaludosMatutinosRequestBody {
        
        public SaludosMatutinosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaludosMatutinosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaludosMatutinosResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteServicio.ProxyServicioTest1.SaludosMatutinosResponseBody Body;
        
        public SaludosMatutinosResponse() {
        }
        
        public SaludosMatutinosResponse(ClienteServicio.ProxyServicioTest1.SaludosMatutinosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaludosMatutinosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SaludosMatutinosResult;
        
        public SaludosMatutinosResponseBody() {
        }
        
        public SaludosMatutinosResponseBody(string SaludosMatutinosResult) {
            this.SaludosMatutinosResult = SaludosMatutinosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JuegoDadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JuegoDado", Namespace="http://tempuri.org/", Order=0)]
        public ClienteServicio.ProxyServicioTest1.JuegoDadoRequestBody Body;
        
        public JuegoDadoRequest() {
        }
        
        public JuegoDadoRequest(ClienteServicio.ProxyServicioTest1.JuegoDadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class JuegoDadoRequestBody {
        
        public JuegoDadoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JuegoDadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JuegoDadoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteServicio.ProxyServicioTest1.JuegoDadoResponseBody Body;
        
        public JuegoDadoResponse() {
        }
        
        public JuegoDadoResponse(ClienteServicio.ProxyServicioTest1.JuegoDadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class JuegoDadoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string JuegoDadoResult;
        
        public JuegoDadoResponseBody() {
        }
        
        public JuegoDadoResponseBody(string JuegoDadoResult) {
            this.JuegoDadoResult = JuegoDadoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceTest1SoapChannel : ClienteServicio.ProxyServicioTest1.WebServiceTest1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceTest1SoapClient : System.ServiceModel.ClientBase<ClienteServicio.ProxyServicioTest1.WebServiceTest1Soap>, ClienteServicio.ProxyServicioTest1.WebServiceTest1Soap {
        
        public WebServiceTest1SoapClient() {
        }
        
        public WebServiceTest1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceTest1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTest1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTest1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteServicio.ProxyServicioTest1.SaludosMatutinosResponse ClienteServicio.ProxyServicioTest1.WebServiceTest1Soap.SaludosMatutinos(ClienteServicio.ProxyServicioTest1.SaludosMatutinosRequest request) {
            return base.Channel.SaludosMatutinos(request);
        }
        
        public string SaludosMatutinos() {
            ClienteServicio.ProxyServicioTest1.SaludosMatutinosRequest inValue = new ClienteServicio.ProxyServicioTest1.SaludosMatutinosRequest();
            inValue.Body = new ClienteServicio.ProxyServicioTest1.SaludosMatutinosRequestBody();
            ClienteServicio.ProxyServicioTest1.SaludosMatutinosResponse retVal = ((ClienteServicio.ProxyServicioTest1.WebServiceTest1Soap)(this)).SaludosMatutinos(inValue);
            return retVal.Body.SaludosMatutinosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteServicio.ProxyServicioTest1.SaludosMatutinosResponse> ClienteServicio.ProxyServicioTest1.WebServiceTest1Soap.SaludosMatutinosAsync(ClienteServicio.ProxyServicioTest1.SaludosMatutinosRequest request) {
            return base.Channel.SaludosMatutinosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteServicio.ProxyServicioTest1.SaludosMatutinosResponse> SaludosMatutinosAsync() {
            ClienteServicio.ProxyServicioTest1.SaludosMatutinosRequest inValue = new ClienteServicio.ProxyServicioTest1.SaludosMatutinosRequest();
            inValue.Body = new ClienteServicio.ProxyServicioTest1.SaludosMatutinosRequestBody();
            return ((ClienteServicio.ProxyServicioTest1.WebServiceTest1Soap)(this)).SaludosMatutinosAsync(inValue);
        }
        
        public double SumarDosNumeros(double numero1, double numero2) {
            return base.Channel.SumarDosNumeros(numero1, numero2);
        }
        
        public System.Threading.Tasks.Task<double> SumarDosNumerosAsync(double numero1, double numero2) {
            return base.Channel.SumarDosNumerosAsync(numero1, numero2);
        }
        
        public double Potencia(double _base, double _exponente) {
            return base.Channel.Potencia(_base, _exponente);
        }
        
        public System.Threading.Tasks.Task<double> PotenciaAsync(double _base, double _exponente) {
            return base.Channel.PotenciaAsync(_base, _exponente);
        }
        
        public int LanzamientoDado() {
            return base.Channel.LanzamientoDado();
        }
        
        public System.Threading.Tasks.Task<int> LanzamientoDadoAsync() {
            return base.Channel.LanzamientoDadoAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteServicio.ProxyServicioTest1.JuegoDadoResponse ClienteServicio.ProxyServicioTest1.WebServiceTest1Soap.JuegoDado(ClienteServicio.ProxyServicioTest1.JuegoDadoRequest request) {
            return base.Channel.JuegoDado(request);
        }
        
        public string JuegoDado() {
            ClienteServicio.ProxyServicioTest1.JuegoDadoRequest inValue = new ClienteServicio.ProxyServicioTest1.JuegoDadoRequest();
            inValue.Body = new ClienteServicio.ProxyServicioTest1.JuegoDadoRequestBody();
            ClienteServicio.ProxyServicioTest1.JuegoDadoResponse retVal = ((ClienteServicio.ProxyServicioTest1.WebServiceTest1Soap)(this)).JuegoDado(inValue);
            return retVal.Body.JuegoDadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteServicio.ProxyServicioTest1.JuegoDadoResponse> ClienteServicio.ProxyServicioTest1.WebServiceTest1Soap.JuegoDadoAsync(ClienteServicio.ProxyServicioTest1.JuegoDadoRequest request) {
            return base.Channel.JuegoDadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteServicio.ProxyServicioTest1.JuegoDadoResponse> JuegoDadoAsync() {
            ClienteServicio.ProxyServicioTest1.JuegoDadoRequest inValue = new ClienteServicio.ProxyServicioTest1.JuegoDadoRequest();
            inValue.Body = new ClienteServicio.ProxyServicioTest1.JuegoDadoRequestBody();
            return ((ClienteServicio.ProxyServicioTest1.WebServiceTest1Soap)(this)).JuegoDadoAsync(inValue);
        }
    }
}
